### PR TITLE
[release-4.15] HOSTEDCP-1513: Support hypershift-operator scoping for hostedclusters

### PR DESCRIPTION
**Pull request by lucaspalm**
This is a manual cherry pick of the changes introduced in https://github.com/openshift/hypershift/pull/3702 and https://github.com/openshift/hypershift/pull/3928 to allow for [Selective Management of HostedCluster Resources via Annotations for Hypershift Operators](https://issues.redhat.com/browse/OCPSTRAT-1300).

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
```
 # github.com/openshift/hypershift/hypershift-operator/controllers/scheduler
hypershift-operator/controllers/scheduler/dedicated_request_serving_nodes.go:98:56: undefined: util 
 FAIL	github.com/openshift/hypershift/hypershift-operator [build failed] 
```

Looks like some cherry-pick errors.

**Comment by lucaspalm** [comment]
It is not clear to me why this last test is failing.  @stevekuznetsov Any ideas?

**Comment by stevekuznetsov** [comment]
/retest

Failed to bring up the mgmt cluster ... @sjenning the [log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_hypershift/3998/pull-ci-openshift-hypershift-release-4.15-e2e-aws/1788296251746291712/artifacts/e2e-aws/create-management-cluster/build-log.txt) might benefit from some more analysis of the HC status, not really actionable right now?
